        !COMPILER-GENERATED INTERFACE MODULE: Wed Dec 19 09:59:36 2012
        MODULE TEMPLATE_READ__genmod
          INTERFACE 
            SUBROUTINE TEMPLATE_READ(FNAME)
              CHARACTER(*), INTENT(IN) :: FNAME
            END SUBROUTINE TEMPLATE_READ
          END INTERFACE 
        END MODULE TEMPLATE_READ__genmod
