.TH "core/m_agcm.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/m_agcm.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBm_agcm::agcm_type_dec\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBm_agcm\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBm_agcm::agcm_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBm_agcm::agcm_read\fP (fname)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(agcm_type_dec) \fBm_agcm::agcm_struc\fP"
.br
.ti -1c
.RI "character(len=*), parameter \fBm_agcm::myname\fP = 'm_agcm'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
