.TH "core/m_time.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/m_time.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBtime_module\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER, public \fBtime_module::eom\fP (year, month)"
.br
.ti -1c
.RI "INTEGER, public \fBtime_module::noh\fP (di, df)"
.br
.ti -1c
.RI "INTEGER, public \fBtime_module::nod\fP (di, df)"
.br
.ti -1c
.RI "INTEGER, public \fBtime_module::nom\fP (di, df)"
.br
.ti -1c
.RI "INTEGER, public \fBtime_module::noy\fP (di, df)"
.br
.ti -1c
.RI "REAL(kind=8), public \fBtime_module::cal2jul\fP (CalDate)"
.br
.ti -1c
.RI "INTEGER(kind=8), public \fBtime_module::jul2cal\fP (jd)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
