.TH "SCAM_gridMOD::griddec" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCAM_gridMOD::griddec \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "real \fBlat\fP"
.br
.ti -1c
.RI "real \fBlon\fP"
.br
.ti -1c
.RI "real \fBlev\fP"
.br
.ti -1c
.RI "integer \fBcol\fP"
.br
.ti -1c
.RI "integer \fBrow\fP"
.br
.ti -1c
.RI "real \fBelev\fP"
.br
.ti -1c
.RI "real \fBdat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file SCAM_gridMOD.f90.
.SH "Member Data Documentation"
.PP 
.SS "integer \fBSCAM_gridMOD::griddec::col\fP"
.PP
Definition at line 62 of file SCAM_gridMOD.f90.
.SS "real \fBSCAM_gridMOD::griddec::dat\fP"
.PP
Definition at line 65 of file SCAM_gridMOD.f90.
.SS "real \fBSCAM_gridMOD::griddec::elev\fP"
.PP
Definition at line 64 of file SCAM_gridMOD.f90.
.SS "real \fBSCAM_gridMOD::griddec::lat\fP"
.PP
Definition at line 59 of file SCAM_gridMOD.f90.
.SS "real \fBSCAM_gridMOD::griddec::lev\fP"
.PP
Definition at line 61 of file SCAM_gridMOD.f90.
.SS "real \fBSCAM_gridMOD::griddec::lon\fP"
.PP
Definition at line 60 of file SCAM_gridMOD.f90.
.SS "integer \fBSCAM_gridMOD::griddec::row\fP"
.PP
Definition at line 63 of file SCAM_gridMOD.f90.

.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
