.TH "SCAM_coreMOD" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCAM_coreMOD \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBSCAM_Config_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBSCAM_Init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBSCAM_RUN\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBSCAM_Finalize\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(len=*), parameter \fBmyname\fP = 'SCAM_coreMod'"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine,public SCAM_coreMOD::SCAM_Config_init ()"
.PP
Definition at line 85 of file SCAM_coreMOD.f90.
.SS "subroutine,public SCAM_coreMOD::SCAM_Finalize ()"
.PP
Definition at line 439 of file SCAM_coreMOD.f90.
.SS "subroutine,public SCAM_coreMOD::SCAM_Init ()"
.PP
Definition at line 148 of file SCAM_coreMOD.f90.
.SS "subroutine,public SCAM_coreMOD::SCAM_RUN ()"
.PP
Definition at line 227 of file SCAM_coreMOD.f90.
.SH "Variable Documentation"
.PP 
.SS "character(len=*),parameter \fBSCAM_coreMOD::myname\fP = 'SCAM_coreMod'"
.PP
Definition at line 71 of file SCAM_coreMOD.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
