.TH "SCAM_Modelplugin" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCAM_Modelplugin \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBSCAM_Models_Plugin\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter, public \fBtemplateId\fP = 0"
.br
.ti -1c
.RI "integer, parameter, public \fBAGCMId\fP = 1"
.br
.ti -1c
.RI "integer, parameter, public \fBEtaId\fP = 2"
.br
.ti -1c
.RI "integer, parameter, public \fBclima50yrId\fP = 3"
.br
.ti -1c
.RI "character(len=*), parameter \fBmyname\fP = 'SCAM_Modelplugin'"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine,public SCAM_Modelplugin::SCAM_Models_Plugin ()"
.PP
Definition at line 65 of file SCAM_ModelPlugin.f90.
.SH "Variable Documentation"
.PP 
.SS "integer,parameter,public \fBSCAM_Modelplugin::AGCMId\fP = 1"
.PP
Definition at line 35 of file SCAM_ModelPlugin.f90.
.SS "integer,parameter,public \fBSCAM_Modelplugin::clima50yrId\fP = 3"
.PP
Definition at line 37 of file SCAM_ModelPlugin.f90.
.SS "integer,parameter,public \fBSCAM_Modelplugin::EtaId\fP = 2"
.PP
Definition at line 36 of file SCAM_ModelPlugin.f90.
.SS "character(len=*),parameter \fBSCAM_Modelplugin::myname\fP = 'SCAM_Modelplugin'"
.PP
Definition at line 48 of file SCAM_ModelPlugin.f90.
.SS "integer,parameter,public \fBSCAM_Modelplugin::templateId\fP = 0"
.PP
Definition at line 34 of file SCAM_ModelPlugin.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
