.TH "core/bilinear_interpolation.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/bilinear_interpolation.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBinterp_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBinterp_mod::bilinear_interp_input\fP (gridDesci, gridDesco, npts, rlat, rlon, n11, n12, n21, n22, w11, w12, w21, w22)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::bilinear_interp\fP (gridDesco, ibi, li, gi, ibo, lo, go, mi, mo, rlat, rlon, w11, w12, w21, w22, n11, n12, n21, n22, udef, iret)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::compute_earth_coord\fP (gridDesc, npts, fill, xpts, ypts, rlon, rlat, nret)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::compute_earth_coord_latlon\fP (gridDesc, npts, fill, xpts, ypts, rlon, rlat, nret)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::compute_earth_coord_gauss\fP (gridDesc, npts, fill, xpts, ypts, rlon, rlat, nret)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::compute_grid_coord\fP (gridDesc, npts, fill, xpts, ypts, rlon, rlat, nret)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::compute_grid_coord_latlon\fP (gridDesc, npts, fill, xpts, ypts, rlon, rlat, nret)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::compute_grid_coord_gauss\fP (gridDesc, npts, fill, xpts, ypts, rlon, rlat, nret)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::gausslat\fP (jmax, slat, wlat)"
.br
.ti -1c
.RI "integer \fBinterp_mod::get_fieldpos\fP (i, j, gridDesc)"
.br
.ti -1c
.RI "subroutine \fBinterp_mod::polfixs\fP (nm, nx, rlat, rlon, ib, lo, go)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
