.TH "core/eta_read.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/eta_read.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBeta_read\fP (fname)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine eta_read (character(len=*),intent(in)fname)"
.PP
Definition at line 1 of file eta_read.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
