.TH "core/Ftable.c" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/Ftable.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br

.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "void \fBft_check_index\fP (int index, int max, char *regrtn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_check_index (intindex, intmax, char *regrtn)"
.PP
Definition at line 29 of file Ftable.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
