.TH "core/SCAM_UtilsMOD.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/SCAM_UtilsMOD.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBSCAM_Utils::domain\fP"
.br
.ti -1c
.RI "type \fBSCAM_Utils::variable\fP"
.br
.ti -1c
.RI "type \fBSCAM_Utils::RUNS\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBSCAM_Utils\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBSCAM_Utils::readcard\fP (istat)"
.br
.ti -1c
.RI "subroutine, public \fBSCAM_Utils::BANNER\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "INTEGER, parameter, public \fBSCAM_Utils::nvmx\fP = 50"
.br
.ti -1c
.RI "INTEGER, parameter, public \fBSCAM_Utils::nlmx\fP = 50"
.br
.ti -1c
.RI "REAL(SP), parameter, public \fBSCAM_Utils::PI\fP = 3.141592653589793238462643383279502884197_sp"
.br
.ti -1c
.RI "REAL(SP), parameter, public \fBSCAM_Utils::PIO2\fP = 1.57079632679489661923132169163975144209858_sp"
.br
.ti -1c
.RI "REAL(SP), parameter, public \fBSCAM_Utils::TWOPI\fP = 6.283185307179586476925286766559005768394_sp"
.br
.ti -1c
.RI "REAL(SP), parameter, public \fBSCAM_Utils::SQRT2\fP = 1.41421356237309504880168872420969807856967_sp"
.br
.ti -1c
.RI "REAL(SP), parameter, public \fBSCAM_Utils::EULER\fP = 0.5772156649015328606065120900824024310422_sp"
.br
.ti -1c
.RI "REAL(DP), parameter, public \fBSCAM_Utils::PI_D\fP = 3.141592653589793238462643383279502884197_dp"
.br
.ti -1c
.RI "REAL(DP), parameter, public \fBSCAM_Utils::PIO2_D\fP = 1.57079632679489661923132169163975144209858_dp"
.br
.ti -1c
.RI "REAL(DP), parameter, public \fBSCAM_Utils::TWOPI_D\fP = 6.283185307179586476925286766559005768394_dp"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::starting_time\fP"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::ending_time\fP"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::time_step\fP"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::Forecast_time\fP"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::ntime_forecast\fP"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::ntime_steps\fP"
.br
.ti -1c
.RI "REAL(DP), public \fBSCAM_Utils::incr\fP"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::hist_time\fP"
.br
.ti -1c
.RI "REAL(DP), public \fBSCAM_Utils::hist_incr\fP"
.br
.ti -1c
.RI "TYPE(domain), dimension(:), allocatable, public \fBSCAM_Utils::dom\fP"
.br
.ti -1c
.RI "TYPE(RUNS), public \fBSCAM_Utils::Refer\fP"
.br
.ti -1c
.RI "TYPE(RUNS), public \fBSCAM_Utils::Clima\fP"
.br
.ti -1c
.RI "INTEGER, public \fBSCAM_Utils::Clima_Flag\fP"
.br
.ti -1c
.RI "TYPE(RUNS), dimension(:), allocatable, public \fBSCAM_Utils::Exper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
