.TH "scamtec_module" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scamtec_module \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBscamdec\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter, public \fBI4B\fP = SELECTED_INT_KIND(9)"
.br
.ti -1c
.RI "integer, parameter, public \fBI2B\fP = SELECTED_INT_KIND(4)"
.br
.ti -1c
.RI "integer, parameter, public \fBI1B\fP = SELECTED_INT_KIND(2)"
.br
.ti -1c
.RI "integer, parameter, public \fBSP\fP = KIND(1.0)"
.br
.ti -1c
.RI "integer, parameter, public \fBDP\fP = KIND(1.0D0)"
.br
.ti -1c
.RI "type(\fBscamdec\fP) \fBscamtec\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "integer,parameter,public \fBscamtec_module::DP\fP = KIND(1.0D0)"
.PP
Definition at line 11 of file scamtec_module.f90.
.SS "integer,parameter,public \fBscamtec_module::I1B\fP = SELECTED_INT_KIND(2)"
.PP
Definition at line 9 of file scamtec_module.f90.
.SS "integer,parameter,public \fBscamtec_module::I2B\fP = SELECTED_INT_KIND(4)"
.PP
Definition at line 8 of file scamtec_module.f90.
.SS "integer,parameter,public \fBscamtec_module::I4B\fP = SELECTED_INT_KIND(9)"
.PP
Definition at line 7 of file scamtec_module.f90.
.SS "type(\fBscamdec\fP) \fBscamtec_module::scamtec\fP"
.PP
Definition at line 42 of file scamtec_module.f90.
.SS "integer,parameter,public \fBscamtec_module::SP\fP = KIND(1.0)"
.PP
Definition at line 10 of file scamtec_module.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
