.TH "core/SCAM_Plugin.c" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/SCAM_Plugin.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <ftn_drv.h>\fP
.br

.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBSCAMTEC_MODEL_INI_TABLE\fP"
.br
.ti -1c
.RI "type \fBSCAMTEC_MODEL_CONFIG_TABLE\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSCAMTEC_MAX_MODEL\fP   (20)"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "void FTN() \fBregistermodelread\fP (int *i, void(*func)())"
.br
.ti -1c
.RI "void FTN() \fBload_data\fP (int *i, char *name)"
.br
.ti -1c
.RI "void FTN() \fBregistermodelinit\fP (int *i, void(*func)())"
.br
.ti -1c
.RI "void FTN() \fBconfig_model\fP (int *i)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSCAMTEC_MODEL_INI_TABLE\fP \fBload_data\fP [SCAMTEC_MAX_MODEL]"
.br
.ti -1c
.RI "\fBSCAMTEC_MODEL_CONFIG_TABLE\fP \fBconfig_model\fP [SCAMTEC_MAX_MODEL]"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define SCAMTEC_MAX_MODEL   (20)"
.PP
Definition at line 9 of file SCAM_Plugin.c.
.SH "Function Documentation"
.PP 
.SS "void FTN() config_model (int *i)"
.PP
Definition at line 63 of file SCAM_Plugin.c.
.SS "void FTN() load_data (int *i, char *name)"
.PP
Definition at line 37 of file SCAM_Plugin.c.
.SS "void FTN() registermodelinit (int *i, void(*)()func)"
.PP
Definition at line 55 of file SCAM_Plugin.c.
.SS "void FTN() registermodelread (int *i, void(*)()func)"
.PP
Definition at line 29 of file SCAM_Plugin.c.
.SH "Variable Documentation"
.PP 
.SS "\fBSCAMTEC_MODEL_CONFIG_TABLE\fP config_model[SCAMTEC_MAX_MODEL]"
.PP
Definition at line 25 of file SCAM_Plugin.c.
.SS "\fBSCAMTEC_MODEL_INI_TABLE\fP load_data[SCAMTEC_MAX_MODEL]"
.PP
Definition at line 17 of file SCAM_Plugin.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
