.TH "SCAM_outputMOD" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCAM_outputMOD \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBwrite_2d\fP (field, fname)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(len=*), parameter \fBmyname\fP = 'SCAM_outputMod'"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine SCAM_outputMOD::write_2d (real,dimension(:,:),intent(in)field, character(len=*),intent(in)fname)"
.PP
Definition at line 35 of file SCAM_outputMOD.f90.
.SH "Variable Documentation"
.PP 
.SS "character(len=*),parameter \fBSCAM_outputMOD::myname\fP = 'SCAM_outputMod'"
.PP
Definition at line 30 of file SCAM_outputMOD.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
