.TH "core/scamtec_module.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/scamtec_module.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBscamtec_module::scamdec\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBscamtec_module\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter, public \fBscamtec_module::I4B\fP = SELECTED_INT_KIND(9)"
.br
.ti -1c
.RI "integer, parameter, public \fBscamtec_module::I2B\fP = SELECTED_INT_KIND(4)"
.br
.ti -1c
.RI "integer, parameter, public \fBscamtec_module::I1B\fP = SELECTED_INT_KIND(2)"
.br
.ti -1c
.RI "integer, parameter, public \fBscamtec_module::SP\fP = KIND(1.0)"
.br
.ti -1c
.RI "integer, parameter, public \fBscamtec_module::DP\fP = KIND(1.0D0)"
.br
.ti -1c
.RI "type(scamdec) \fBscamtec_module::scamtec\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
