.TH "core/SCAM_ModelPlugin.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/SCAM_ModelPlugin.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBSCAM_Modelplugin\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBSCAM_Modelplugin::SCAM_Models_Plugin\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter, public \fBSCAM_Modelplugin::templateId\fP = 0"
.br
.ti -1c
.RI "integer, parameter, public \fBSCAM_Modelplugin::AGCMId\fP = 1"
.br
.ti -1c
.RI "integer, parameter, public \fBSCAM_Modelplugin::EtaId\fP = 2"
.br
.ti -1c
.RI "integer, parameter, public \fBSCAM_Modelplugin::clima50yrId\fP = 3"
.br
.ti -1c
.RI "character(len=*), parameter \fBSCAM_Modelplugin::myname\fP = 'SCAM_Modelplugin'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
