.TH "core/ftn_drv.h" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/ftn_drv.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFTN\fP(func)   func"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FTN(func)   func"
.PP
Definition at line 14 of file ftn_drv.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
