.TH "m_clima50yr" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_clima50yr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBclima50yr_type_dec\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBclima50yr_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBclima50yr_read\fP (fname)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(clima50yr_type_dec) \fBclima50yr_struc\fP"
.br
.ti -1c
.RI "character(len=*), parameter \fBmyname\fP = 'm_clima50yr'"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine,public m_clima50yr::clima50yr_init ()"
.PP
Definition at line 37 of file m_clima50yr.f90.
.SS "subroutine,public m_clima50yr::clima50yr_read (character(len=*),intent(in)fname)"
.PP
Definition at line 107 of file m_clima50yr.f90.
.SH "Variable Documentation"
.PP 
.SS "type(clima50yr_type_dec) \fBm_clima50yr::clima50yr_struc\fP"
.PP
Definition at line 25 of file m_clima50yr.f90.
.SS "character(len=*),parameter \fBm_clima50yr::myname\fP = 'm_clima50yr'"
.PP
Definition at line 33 of file m_clima50yr.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
