.TH "core/m_string.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/m_string.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBm_string\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBm_string::str_template\fP (strg, nymd, nhms, fymd, fhms)"
.br
.ti -1c
.RI "subroutine, public \fBm_string::replace_\fP (strg, mask, repl)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CHARACTER(len=3), dimension(12), parameter \fBm_string::mon_lc\fP = (/ 'jan','feb','mar','apr','may','jun', 'jul','aug','sep','oct','nov','dec'/)"
.br
.ti -1c
.RI "CHARACTER(len=3), dimension(12), parameter \fBm_string::mon_wd\fP = (/ 'Jan','Feb','Mar','Apr','May','Jun', 'Jul','Aug','Sep','Oct','Nov','Dec'/)"
.br
.ti -1c
.RI "CHARACTER(len=3), dimension(12), parameter \fBm_string::mon_uc\fP = (/ 'JAN','FEB','MAR','APR','MAY','JUN', 'JUL','AUG','SEP','OCT','NOV','DEC'/)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
