#!/bin/sh
ROOT_DIR=`pwd`
while true
do
echo "------------------choose one of options-----------------"
echo
echo " 1 - Clean Environment"
echo ""
echo " 2 - PGI XE - Load PGI Environment to XT/XE and compile"
echo ""
echo " 3 - INTEL - Load INTEL Environment to LINUX and compile"
echo ""
echo " E - Exit"
#
echo
echo -n "Choose one of options (1-E): "
read option
echo
case $option in
#
[1])
echo "------------------cleanning environment-----------------"
echo
cd $ROOT_DIR; make clean
echo
echo "-------------------environment cleaned------------------"
echo
continue
;;
#
[2])
echo "--------------------loading environment-----------------"
echo
export SCAM_ARCH=cray_pgi
echo SCAM_ARCH=$SCAM_ARCH
echo
echo "--------------------environment loaded------------------"
echo
;;
#
[3])
echo "--------------------loading environment-----------------"
echo
export SCAM_ARCH=Darwin_intel
echo SCAM_ARCH=$SCAM_ARCH
echo
echo "--------------------environment loaded------------------"
echo
;;
#
[E])
echo
echo "--------------------------exiting-----------------------"
echo
break
;;
#
*)
echo "invalid option"
;;
esac
cd $ROOT_DIR; make
break
done
