        !COMPILER-GENERATED INTERFACE MODULE: Wed Dec 19 09:59:36 2012
        MODULE ETA_READ__genmod
          INTERFACE 
            SUBROUTINE ETA_READ(FNAME)
              CHARACTER(*), INTENT(IN) :: FNAME
            END SUBROUTINE ETA_READ
          END INTERFACE 
        END MODULE ETA_READ__genmod
