.TH "m_string" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_string \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBstr_template\fP (strg, nymd, nhms, fymd, fhms)"
.br
.ti -1c
.RI "subroutine, public \fBreplace_\fP (strg, mask, repl)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CHARACTER(len=3), dimension(12), parameter \fBmon_lc\fP = (/ 'jan','feb','mar','apr','may','jun', 'jul','aug','sep','oct','nov','dec'/)"
.br
.ti -1c
.RI "CHARACTER(len=3), dimension(12), parameter \fBmon_wd\fP = (/ 'Jan','Feb','Mar','Apr','May','Jun', 'Jul','Aug','Sep','Oct','Nov','Dec'/)"
.br
.ti -1c
.RI "CHARACTER(len=3), dimension(12), parameter \fBmon_uc\fP = (/ 'JAN','FEB','MAR','APR','MAY','JUN', 'JUL','AUG','SEP','OCT','NOV','DEC'/)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine,public m_string::replace_ (CHARACTER(len=*),intent(inout)strg, CHARACTER(len=*),intent(in)mask, CHARACTER(len=*),intent(in)repl)"
.PP
Definition at line 208 of file m_string.f90.
.SS "subroutine,public m_string::str_template (CHARACTER(len=*),intent(inout)strg, INTEGER,intent(in)nymd, INTEGER,intent(in)nhms, INTEGER,intent(in),optionalfymd, INTEGER,intent(in),optionalfhms)"
.PP
Definition at line 101 of file m_string.f90.
.SH "Variable Documentation"
.PP 
.SS "CHARACTER(len=3),dimension(12),parameter \fBm_string::mon_lc\fP = (/ 'jan','feb','mar','apr','may','jun', 'jul','aug','sep','oct','nov','dec'/)"
.PP
Definition at line 33 of file m_string.f90.
.SS "CHARACTER(len=3),dimension(12),parameter \fBm_string::mon_uc\fP = (/ 'JAN','FEB','MAR','APR','MAY','JUN', 'JUL','AUG','SEP','OCT','NOV','DEC'/)"
.PP
Definition at line 41 of file m_string.f90.
.SS "CHARACTER(len=3),dimension(12),parameter \fBm_string::mon_wd\fP = (/ 'Jan','Feb','Mar','Apr','May','Jun', 'Jul','Aug','Sep','Oct','Nov','Dec'/)"
.PP
Definition at line 37 of file m_string.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
