.TH "SCAM_bstatistic" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCAM_bstatistic \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcorr\fP (X, Y, Rho)"
.br
.ti -1c
.RI "subroutine \fBstdize\fP (Z, Zmean, Zsdev, Zanom)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine SCAM_bstatistic::corr (Real,dimension(:,:),intent(in)X, Real,dimension(:,:),intent(in)Y, Real,intent(out)Rho)"
.PP
Definition at line 12 of file SCAM_bstatistic.f90.
.SS "subroutine SCAM_bstatistic::stdize (Real,dimension(:,:),intent(in)Z, Real,dimension(:),intent(out)Zmean, Real,dimension(:),intent(out)Zsdev, Real,dimension(:,:),intent(out)Zanom)"
.PP
Definition at line 52 of file SCAM_bstatistic.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
