.TH "SCAMTEC_MODEL_INI_TABLE" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCAMTEC_MODEL_INI_TABLE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBfunc\fP )(char *, int slen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file SCAM_Plugin.c.
.SH "Member Data Documentation"
.PP 
.SS "void(* \fBSCAMTEC_MODEL_INI_TABLE::func\fP)(char *, int slen)"
.PP
Definition at line 13 of file SCAM_Plugin.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
