.TH "core/SCAM_bstatistic.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/SCAM_bstatistic.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBSCAM_bstatistic\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBSCAM_bstatistic::corr\fP (X, Y, Rho)"
.br
.ti -1c
.RI "subroutine \fBSCAM_bstatistic::stdize\fP (Z, Zmean, Zsdev, Zanom)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
