.TH "core/SCAM_dataMOD.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/SCAM_dataMOD.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBSCAM_dataMOD::model_dec_type\fP"
.br
.ti -1c
.RI "type \fBSCAM_dataMOD::obs_dec_type\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBSCAM_dataMOD\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBSCAM_dataMOD::data_config\fP ()"
.br
.ti -1c
.RI "subroutine \fBSCAM_dataMOD::allocate_data_mem\fP ()"
.br
.ti -1c
.RI "subroutine \fBSCAM_dataMOD::data_init\fP ()"
.br
.ti -1c
.RI "subroutine \fBSCAM_dataMOD::release_data_mem\fP ()"
.br
.ti -1c
.RI "subroutine \fBSCAM_dataMOD::ldata\fP (type, e, Id, name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter, public \fBSCAM_dataMOD::NumVarAval\fP = 15"
.br
.ti -1c
.RI "character(len=8), parameter, public \fBSCAM_dataMOD::VarName\fP = (/ 'VTMP:925', 'VTMP:850', 'VTMP:500', 'PSNM:000', 'UMES:925', 'AGPL:925', 'ZGEO:850', 'ZGEO:500', 'ZGEO:250', 'UVEL:850', 'UVEL:500', 'UVEL:250', 'VVEL:850', 'VVEL:500', 'VVEL:250' /)"
.br
.ti -1c
.RI "type(model_dec_type), dimension(:), allocatable, public \fBSCAM_dataMOD::scamdata\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
