.TH "m_agcm" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_agcm \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBagcm_type_dec\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBagcm_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBagcm_read\fP (fname)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(agcm_type_dec) \fBagcm_struc\fP"
.br
.ti -1c
.RI "character(len=*), parameter \fBmyname\fP = 'm_agcm'"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine,public m_agcm::agcm_init ()"
.PP
Definition at line 35 of file m_agcm.f90.
.SS "subroutine,public m_agcm::agcm_read (character(len=*),intent(in)fname)"
.PP
Definition at line 102 of file m_agcm.f90.
.SH "Variable Documentation"
.PP 
.SS "type(agcm_type_dec) \fBm_agcm::agcm_struc\fP"
.PP
Definition at line 23 of file m_agcm.f90.
.SS "character(len=*),parameter \fBm_agcm::myname\fP = 'm_agcm'"
.PP
Definition at line 31 of file m_agcm.f90.
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
