.TH "core/SCAM_coreMOD.f90" 3 "Wed May 9 2012" "Version v0.1" "SCAMTEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/SCAM_coreMOD.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBSCAM_coreMOD\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBSCAM_coreMOD::SCAM_Config_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBSCAM_coreMOD::SCAM_Init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBSCAM_coreMOD::SCAM_RUN\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBSCAM_coreMOD::SCAM_Finalize\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(len=*), parameter \fBSCAM_coreMOD::myname\fP = 'SCAM_coreMod'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SCAMTEC from the source code.
